brittanyrw/emojipages

data.js
=> added The Girl with the Dragon Tattoo

app.js
=> Add basic keyboard accessibility to each card

data.js
=> Issue 44: adding Winne the pooh book data

data.js
Addressing https://github.com/brittanyrw/emojipages/issues/71
=> Added Freaky Friday

data.js
=> Added "War of the Worlds" 

data.js
=> Added Fight Club

data.js
=> Added Animal Farm

data.js
=> Added Life of Pi

data.js
=> Added The Shining

data.js
=> Added Dune

data.js
=> Added the perks of being a wallflower

data.js
=> Added "Of Mice and Men", John Steinbeck, Issue# 98

data.js
Wiki: https://en.wikipedia.org/wiki/Harry_Potter_and_the_Methods_of_Rationality
=> Added Harry Potter and the Methods of Rationality

data.js
=> Added "IT" by Stephen King - Issue #87

data.js
#10 
<!-- 👋 If this pull request closes an issue, add the note 'Closes #---' to the bottom of the pull request (replace the --- with the issue number) Only add this if you have completed the entire issue, do not add if you have only partially completed the issue.
=> Add New Moon

data.js
=> added harry potter and the chamber of secrets

data.js
=> Add "The Princess Bride"

data.js
=> fix 47 add "The Color Purple"

data.js
<!-- 👋 If this pull request closes an issue, add the note 'Closes #---' to the bottom of the pull request (replace the --- with the issue number) Only add this if you have completed the entire issue, do not add if you have only partially completed the issue. 
Closes #61
=> Added The Very Hungry Caterpillar

data.js
- [👍 ] 👍 My pull request has a descriptive title (such as `Added Matilda` or `Added all of Jane Austen's books`)
- [👍 ] 🕵🏽‍♀️ I have searched the `data.js` file and confirmed I am not adding a duplicate entry.
- [ 👍] 💜 I have checked Issues and Pull Requests to confirm I am not adding a duplicate entry that is pending approval.
- [👍 ] 🖍️ I have placed the new books(s) or play(s) in alphabetical order based on `title` inside of the `data.js` file. 
- [👍 ] 4️⃣ I have at least four emojis listed under `emojiImgs`
- [👍 ] 6️⃣ I have a maximum of six emojis listed under `emojiImgs`.
- [👍 ] ⭐ My genres are all inside of square brackets `[ ]` and each are individually wrapped in quotation marks and have a comma between each one. (such as submitting this `"genres": ["fantasy", "children", …
=> Added books

data.js
<!-- 👋 If this pull request closes an issue, add the note 'Closes #---' to the bottom of the pull request (replace the --- with the issue number) Only add this if you have completed the entire issue, do not add if you have only partially completed the issue.
=> added death of a salesman

data.js
=> Add Monsieur Malaussène

data.js
=> Added The Little Prince by Antoine de Saint-Exupery

data.js, pull_request_template.md
=> The Adventures of Sherlock Holmes" by Sir Arthur Conan Doyle to EmojiPages #100

data.js
=> added dumbo

data.js
[@christerseiler](https://twitter.com/christerseiler)
=> added CloudAtlas - Closes #112

app.js, index.html, main.css
- Added a `filters` _section_ on the html to contain filter options.
- Added a `message` _section_ to show when no were found by the selected filter
- Added a `genreFilters` _array_ to store all the genre filters
- Added a `addFilter` _function_ to add filters to an array of filters if the filter doesnt exist already
- Added a `addFilterFromGenres` _function_ to add filters from the genres.md file making an ajax request
- Added a `initGenreFilter` _function_ to initialize the genre filters from the genreFilters arrays
- Added a `handleGenreFilterChange` _function_ to handle the selection change from the dropdown
- Added a `sortAlphabetical` _function_ to sort an array by asc/dsc
- Added a `.filters` _class_ for the filters section
- Added `.filters-heading` `.filters-options` _classes_ …
=> Add dropdown to filter section for genre filtering

data.js
*Added The Wind-Up Bird Chronicle by Haruki Murakami
=> Added The Wind-Up Bird Chronicle by Haruki Murakami

index.html, main.css
Hello, I've added the link requested in issue #275. I didn't know if you wanted something a bit more interesting in terms of design so I tried to make it very similar to the screenshot you posted from emojibops.
If there is any changes or additions you would like me to add, I would be happy to do so.
=> Added a link to the goodreads shelf on the front page

data.js
Steelheart by Brandom Sanderson
The Matrix by Wachowski Brothers
=> Adding Steelheart

data.js
now they are books ,sorry for my absence of mind :)
=> Adding Don Quixote, Into the Wild and The Trial cards

data.js
- Added The Book Thief
- Added Crazy Rich Asians
- Added The Fault in Our Stars
- Added Percy Jackson and the Lightning Thief
=> Added Young Adult books

app.js, data.js, docs/card_overview.md, docs/github_ui_walkthrough.md, docs/local_dev_walkthrough.md
This PR handles the new property `itemLink` on each book entry and create a link with its value that opens in a new tab. It updates some docs too.
The list of tasks addressed in the PR comes from the issue #269:
Closes #269
=> Render link to GoodReads

data.js
=> Adding Diamond Age by Neal Stephenson 

data.js
Add itemLink URL to Goodreads for books A-B
=> Add itemLink in data.js

data.js
Added the eye of the world which I'm currently reading :)
=> feat(eotw): add The Eye of the World entry

data.js
=> Add The Secret Garden & The Wizard of Oz

data.js, genres.md
Added a new genre, post-apocalyptic fiction, also.
Third time, hopefully this will be the lucky!
=> Added The Road by Cormac McCarthy and The Gruffalo, by Julia Donaldson

data.js
Add Dracula, Little Women, Pride and Prejudice to emojipages
=> Add novels to data.js
